name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - uses: actions/checkout@v3

      # Passo 2: Configuração do JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Passo 3: Download do JAR do H2 Database
      - name: Download H2 Database JAR
        run: |
          wget -O h2.jar https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar

      # Passo 4: Inicialização do H2 Database
      - name: Start H2 Database
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          java -cp h2.jar org.h2.tools.Server -webAllowOthers -tcpAllowOthers -ifNotExists -baseDir ./data/demo &

      # Passo 5: Build e Teste
      - name: Build and Test
        run: mvn clean test

      # Passo 6: Parar o H2 Database
      - name: Stop H2 Database
        run: pkill -f "java.*h2.jar"