name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Start H2 Database
      env:
        DATABASE_USER: sa
        DATABASE_PASSWORD: password
        DATABASE_URL: jdbc:h2:file:/data/demo
      run: |
        docker run -d -p 8080:8080 -e H2_OPTIONS=’-ifNotExists’ -e H2_USER=$DATABASE_USER -e H2_PASSWORD=$DATABASE_PASSWORD -e H2_URL=$DATABASE_URL -v $(pwd)/data:/data –rm oscarfonts/h2
        
    - name: Build and Test
      run: mvn clean test

    - name: Stop H2 Database
      run: docker stop h2db

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
